# Generated by Django 4.1.7 on 2023-03-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_post_views_connection"),
    ]

    operations = [
        migrations.CreateModel(
            name="keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="profiles",
        ),
    ]
