# Generated by Django 4.1.7 on 2023-03-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_keywords_delete_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="keywords",
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(to="accounts.skill"),
        ),
    ]
