# Generated by Django 4.1.7 on 2023-03-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_savedpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="keywords",
        ),
        migrations.AddField(
            model_name="post",
            name="skills",
            field=models.ManyToManyField(to="accounts.skill"),
        ),
    ]
