# Generated by Django 4.1.7 on 2023-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_post_keywords_post_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="abstract",
            field=models.CharField(max_length=2000),
        ),
    ]
