# Generated by Django 4.1.7 on 2023-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allow_downloading',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='paper',
            field=models.FileField(blank=True, default=None, upload_to='papers/'),
        ),
    ]
