# Generated by Django 4.1.7 on 2023-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_post_allow_downloading_alter_post_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allow_downloading',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paper',
            field=models.FileField(blank=True, default=None, null=True, upload_to='papers/'),
        ),
    ]
