# Generated by Django 4.1.7 on 2023-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_post_allow_downloading_alter_post_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allow_downloading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='paper',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
