# Generated by Django 4.1.7 on 2023-06-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_post_uploaded_by_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='assignment',
            new_name='post',
        ),
    ]
