# Generated by Django 4.1.7 on 2023-07-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='p_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='accounts.comment'),
        ),
    ]
