# Generated by Django 4.1.7 on 2023-07-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_comment_p_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='p_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_content',
            field=models.TextField(blank=True),
        ),
    ]
