# Generated by Django 4.1.7 on 2023-07-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_comment_p_comment_comment_reply_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_content',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
