# Generated by Django 4.1.7 on 2023-08-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_post_keywords_alter_post_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
