# Generated by Django 4.1.7 on 2023-07-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_comment_on_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='on_project',
        ),
    ]
