# Generated by Django 4.1.7 on 2023-07-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_comment_on_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='on_project',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
