# Generated by Django 4.1.7 on 2023-07-22 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0053_comment_on_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='on_project',
        ),
        migrations.AddField(
            model_name='post',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='on_project',
            field=models.BooleanField(default=False),
        ),
    ]
