# Generated by Django 4.1.7 on 2023-08-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_collaborationnotification_collaboration_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationnotification',
            name='collaboration_post',
        ),
    ]
